### ISSUE TITLE
I uploaded all the data, how I can upload to the web?

### ISSUE THREAD

**Issue by nexomad** [BSData/super-hero-universe#1]
Hi @amis92!
Finally I have time to complete the upload of my Super Hero Universe and Batman Miniature Game files. I think I did it, how can I upload to http://battlescribedata.appspot.com/#/repos?

**Comment by amis92** [comment]
Here you go: https://github.com/BSData/bsdata/wiki/Developer-Guide#releasing

If still in doubt, ask!

**Comment by nexomad** [comment]
Hi @amis92! Thanks for the info, I released the version. So now I have to wait until I can see in the main page of Battlescribe Data, no? How often is this auto-update?
